# Lecture 2: Introduction to NumPy and Pandas

Data science and machine learning rely on the ability to easily manipulate large amounts of data and efficiently do numerical calculations on this data. This has resulted in the development of several libraries that specialise in addressing this problem. The strength of the Python 'ecosystem' is that these libraries usually work well together. A central part of the Python ecosystem for data science is the combination of **NumPy** ('Numerical Python') and **Pandas** ('Python Data Analysis Library').

NumPy is the block upon which Pandas is built, so in this chapter, we will briefly explore the main concepts of using NumPy and NumPy arrays. We will then focus on Pandas, an extremely useful library for organising and exploring your data; you will be using this library extensively throughout the rest of the course. If there's one thing I'd like to you learn from this course, it's the ability to use Pandas for your data analysis projects!

## Learning Objectives
1. Understand how array computing avoids bugs and speeds up analysis
2. Basics of NumPy NDArrays
3. Loading data in Pandas
4. Basic terminology of Pandas Series and Dataframes
5. Obtaining basic statistics from dataframes
6. Numerical computation with dataframes
7. Merging data and deleting data


## 2.0 General Introduction to NumPy
<a id="intro"></a>

In [ ]:
from IPython.display import IFrame
display(IFrame('https://youtube.com/embed/NLqkYpK0PsI', width = 640, height = 360))

## 2.1 Introduction to NumPy <a id="npintro"></a>

NumPy is a library for the Python programming language that adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. NumPy was formally created in 2005 by Travis Oliphant but incorporates features of the competing former libraries, such as Numarray and Numeric, with extensive modifications. NumPy is open-source software and has many contributors.

Let's explore how NumPy works. First, let's make sure you are familiar with how to import external libraries into a notebook. Feel free to skip to the next section if you are familiar with this.

Before you can import a library into your notebook, you need to install it into your system. We did this last week (that whole with the `requirements.txt`). If you want to learn more about this (it's not very complicated) you can check the documentation for the ['pip install' command](https://pip.pypa.io/en/stable/reference/pip_install/) or the ['conda install' command](https://docs.conda.io/projects/conda/en/latest/commands/install.html), depending on whether you are using a regular distribution of Python or an Anaconda distribution of Python.

Once a library is installed locally on your system, you can use the `import` command to import the library into your Notebook. You will need to do this for any library you want to use in a notebook (or in your VSCode file). You did not have to do this up to now because you only used standard Python commands in **Lecture 1**. However, NumPy and Pandas are not standard packages in every Python distribution. The syntax to import an entire library is easy:

```python
import name_of_library as local_name_you_want
```

The local name is a shorthand or alias that you can use in your notebook. You only need to import a library once per notebook for it to be available in all of your cells. The NumPy library name is `numpy` (case sensitive) and it is convention to use the alias `np` for it (remember that the appropriate use of conventions will be taken into account during marking!). Following conventions ensures your code is more readable: so stick to it. So let's import the libary:

In [1]:
import numpy as np

Now let's go straight to business with why NumPy is so important. Below we will use NumPy's `arange` method  to create a NumPy array containing 1 million numbers. We will also create a plain vanilla Python list containing the same 1 million numbers. Let's do this now:

In [2]:
my_arr = np.arange(1000000) # The NumPy way -> we obtain an NumPy NDArray
my_list = list(range(1000000)) # Plain Python -> We obtain a simple Python list

The goal is to compare the speed of arithmetic operations between NumPy arrays and plain vanilla Python lists. Remember that NumPy is backed by linear algebra (matrix operations) and is written in C (a low-level compiled language). Plain vanilla Python is an interpreted language, so every command needs to be interpreted first before it is run.

We will use a magic command ('%') called `time` which returns the time that the computer takes to process a given command. Let's first multiply the numbers by 2 using the NumPy calculation and timing it:

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 14.4 ms, sys: 13.5 ms, total: 27.9 ms
Wall time: 25.9 ms


Now let's do that same using plain vanilla Python and a list comprehension:

In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 188 ms, sys: 52.7 ms, total: 241 ms
Wall time: 239 ms


And this was a very simple operation, on 'only' 1 million numbers. On my system, the plain vanilla Python is about 20 times slower. It should now be clear to you why NumPy and Pandas (which uses NumPy behind the scenes) are so important.

## 2.2 The NumPy ndarray: A Multidimensional Array Object <a id="intro"></a>

Under the hood, the field of data science and machine learning is concerned with vectors, matrix, and tensor operations (don't be afraid if you don't know what these mean - we'll introduce these to you slowly over the course). NumPy provides us with a tool to conduct these operations: an `ndarray` or multi-dimensional array object. You used an `ndarray` in your previous exercise.

In [7]:
from IPython.display import IFrame
display(IFrame('https://youtube.com/embed/eSMb1Xe2svM', width = 640, height = 360))

### 2.2.1 Creating ndarrays <a id="creatingarrays"></a>

Arrays can easily be created using the 'array' method of NumPy:

In [8]:
# Let's create a Python list
data1 = [6, 7.5, 8, 0, 1]

# And turn it into an array - note the formatting of the array and how it compares to lists and tuples
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

The preceding example shows how to create a vector, i.e. a 1D array. We can create 2D arrays by giving a nested list of lists to NumPy:

In [9]:
#
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

We can confirm the dimensions of our array by using the `ndim` method:

In [11]:
arr2.ndim

2

And we can see the `shape` of our array, i.e. the size of each dimension, by calling the 'shape' method:

In [10]:
arr2.shape

(2, 4)

Note that the `shape` method returns a tuple, with the first element being the number of rows, and the second being the number of columns.

We see above that the shape of my array is a matrix (2 dimensions) of vectors of dimension 4. Because shape returns a tuple, I can extract the dimension of any axis by giving an argument to the return value. For instance, here I can extract the dimension of the second axis:

In [12]:
arr2.shape[1]

4

To create an array with a range of numbers, use the `arange` method:

In [ ]:
np.arange(100)

You can also give a starting value, end value, and step size to the `arange` function. 

One more very useful Jupyter Notebook trick is to place your cursor immediately after the opening parenthesis of a function and press Shift-Tab: this will allow you to see the documentation of the function, including the arguments it takes, and what the function returns. Some documentation even gives you examples of how to use the function.

The code below will create an `ndarray` starting at 50 and ending at 100 (not inclusive of the last value), and storing every second number (i.e., a step size of 2):

In [ ]:
np.arange(50,100,2)

### 2.2.2 Arithmetic with NumPy Arrays <a id="numpyarithmetic"></a>

One of the most powerful features of NumPy is that you can treat arrays (and thus matrices and tensors) as you would scalars, and thus you can do batch operations very efficiently. Let's demonstrate with an example:

In [13]:
# Let's create a 2D array
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

If we multiply two arrays, the result is that each number in the first array is multiplied by the number in the same position in the second array. This is known as an **element-wise operation**. So for instance we can square our array:

In [14]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

And if we subtract values, the same rule applies. Try to predict the result of this cell before you run it.

In [ ]:
arr - arr

Arithmetic operations that use scalars propagate the scalar in the operation. For instance, the math below will result in 1/x for all x's in the array:

In [ ]:
1 / arr

And this will put each number in the array to the power of 0.5, which is the same as a square root

In [ ]:
arr ** 0.5

### 2.2.3 Mathematical and Statistical Methods <a id="npstatisticalmethods"></a>

NumPy arrays come with a range of built-in mathematical and statistical methods that can be extremely useful. Let's first create an array of random numbers. **Bonus**: Use Shift-Tab on the `randn` function (or any other function) to see what exactly it's doing behind the scenes, such as how exactly it is generating these random numbers.

In [ ]:
arr = np.random.randn(5, 4)
arr

We can easily find the mean of the array with this method:

In [ ]:
arr.mean()

We can also find the sum of all the elements in the array:

In [ ]:
arr.sum()

But what if we are only interested in the sum mean per column? In such cases, we pass an `axis` parameter to the method. In a two-dimensional array, rows are on axis 0 while columns on axis 1. More complex ndarrays can have additional axis (any number of them!). Taking the mean of each column results in an array of a lower dimension, in our case, a row vector:

In [ ]:
arr.mean(axis=0)

This will produce the sum along each column:

In [ ]:
arr.sum(axis=1)

Sometimes it can be useful to look at the cumulative sum at each location in your array, starting from position zero.
`cumsum` will do just that, add the previous value to the local value in the array, and propagate the result forward

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

Of course you can also do this on a single axis. Let's create a martix and take the cumulative sum along axis 0:

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [ ]:
arr.cumsum(axis=0)

We can also do a cumulative product. Let's do this along the column axis this time:

In [ ]:
arr.cumprod(axis=1)

## 2.2.4 Reshaping arrays <a id="reshaping"></a>

In some cases, you might want to reshape an array from a 1D array to a 2D array, or vice versa. Numpy has a useful `reshape` method for this very purpose. All you need to do is provide the dimensions of the array that you want:

In [15]:
# Create a 1D array:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Reshape the array into a 3x3 2D matrix. 
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Note that reshaping returns you a new 2D array - it does NOT make changes to the original array:
arr

In [17]:
# What happens when you try to reshape the array into a 2D object that doesn't fit with the number of elements?
arr.reshape(4,2)

ValueError: cannot reshape array of size 9 into shape (4,2)

Sometimes, you'll know that you want to reshape your array into something that has 3 rows, but you're not sure how many columns the final array would have. Thankfully, the `reshape` function can calculate this for you! All you need to do is fill in the unknown dimension with -1:

In [18]:
arr = np.arange(1,13)

arr.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# This works on both dimensions:
arr.reshape(-1, 3)

Another simple method that can be used to reorder your arrays include `.T`, which transposes your 2D array. There are many in-built NumPy functions that can manipulate your arrays, such as `np.fliplr()` or `np.flipud()`. Experiment with these to see what they do to your array.

In [ ]:
arr2 = arr.reshape(3,4)
arr2

In [ ]:
# What does a transposed array look like? See if you predict the result before running the code!
arr2.T

## 2.2.5 Indexing and slicing arrays <a id="slicing"></a>

It is often useful to 'slice' an array to obtain a smaller, subarray. Whilst doing this, you might also obtain an array with different indexes. As usual for Python, ndarrays use zero-indexing - in other words, the first element in the array has position 0. Let's first look at a simple case where we slice a 1D array. This is not so different from slicing a Python list:

In [19]:
# Create an array
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Slice from 3-4, i.e. start at position 3 and stop at position 4 (remember the last position is not included):
my_arr[3:5]

array([3, 4])

In [21]:
# If you omit one of the two terms of the slice, you obtain all values from/to the value you give:
my_arr[:5]

array([0, 1, 2, 3, 4])

In [22]:
# Or from the 5th position to the end:
my_arr[4:]

array([4, 5, 6, 7, 8, 9])

Note that NumPy arrays can also be sliced and indexed from the last position. So for instance, if I want to know the value of the last element in my array, I don't need to know its size; I can simply do this:

In [23]:
my_arr[-1]

9

And of course, I can slice the array in the same way. For instance, here I take everything from the 2nd (position 1 with zero indexing) to the 6th position (10-3 but the last value is not included):

In [24]:
my_arr[1:-3]

array([1, 2, 3, 4, 5, 6])

Arrays with higher dimensions are a bit more tricky to deal with.

In [ ]:
my_arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_arr2

In [ ]:
# You can extract the columns (axis 1) of this data very simply:
my_arr2[0]

In [ ]:
# You can slice as well, to obtain the first 2 columns for instance:
my_arr2[0:2]

In [ ]:
# You can also slice through the higher dimensions by adding a slice argument separated by a comma. For instance, this 
# slice will give you the first row of the first 2 columns:
my_arr2[0:2,0:1]

## Exercise 1 
<a id="x1"></a>

You now have all the elements to do meaningful calculations using ndarrays. We will apply this to a simple example. You are asked to calculate the sedimentation rate in a given well. For this, you are provided with an ndarray with two dimensions (i.e., a matrix). The first vector column represents the depth of a stratigraphic marker [**in meters**] below the seafloor. The second column represents the age of the marker in millions of years.

You have two objectives in this exercise:
1. To produce a matrix that shows the sedimentation rate between each marker in **cm/kyr**. Note that the units are different than the units you were given above, so you will need to account for that.
2. I also want to know what the average sedimentation for this site is.

Exercise parameters:
1. You cannot use any type of loops
2. As a hint, you will need to use indexing and slicing. 
3. Keep in mind that you can make several different slices from the original dataset. 
4. In addition, don't lose sight of the fact that a sedimentation rate is calculated *between* two points in a well. So if you have n age points, there will be n-1 sedimentation rates

**Hint**: You may want to look up numpy's documentation to see if there is a simple NumPy function that does what you want. This is an important part of problem-solving in Data Science - the ability to efficiently search documentation to see if there are tools that you can use to make your life easier, rather than coding them yourself!

That said, it *is* possible to complete this exercise without using any new functions!

In [ ]:
# The ndarray below represents age in the first row vs burial depth in the second row
age_vs_depth = np.array([[0.5,2.1,3.0,6.1,9.3,12.4,15.3,16.2,16.3,20.1,40.2,41.3,55.2],
                         [15.0,35.0,100.3,160.3,180.4,220.5,241.2,255.0,258.3,312.1,312.2,320.3,380.1]])



In [ ]:
#Your Code:

Take a look at your results - is there a datapoint that you might want to ask your colleagues to investigate in more detail?

## 2.3 Getting Started with pandas <a id="intropandas"></a>

Pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, Pandas gives Python programmers the ability to manipulate **tabular data** and **time series** using several unique data structures and operations. It is free software released under the three-clause BSD license. The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individual observations. Its name is a play on the phrase "Python data analysis". Wes McKinney started building what would become Pandas at AQR Capital while he was a researcher there from 2007 to 2010.

In [ ]:
from IPython.display import IFrame
display(IFrame('https://youtube.com/embed/jox3od5OB4k', width = 640, height = 360))

Let's first import the entire `pandas` library. By convention, `pandas` is imported as the alias `pd`. However, we also want to be able to refer to the `Series` and `DataFrame` objects in Pandas, so we will also import specifically these from Pandas. For this, we use this syntax:

```python
from your_library import object1, object2, ..., objectX
```

In [ ]:
import pandas as pd
from pandas import Series, DataFrame

### 2.3.1 Reading Data into Pandas <a id="readpandas"></a>

Most computing courses start with programmatic examples involving turning simple arrays into Pandas objects. However, we are interested in geological data: rather than starting with abstract arrays that don't really mean anything, we can dive straight into using *REAL* geological data and learn how to import this data into Pandas before playing around with it.

The data I selected is real geochemical data collected from the Ocean Drilling Program (ODP) Leg 198 (Walvis Ridge), specifically from ODP Site 1207. The data is stored as a comma-separated text file (a `.csv` file) in the `Data` folder where this notebook is located. `.csv` files are one of the most common ways in which data is stored - get used to working with it!

Opening a dataset in Pandas is relatively straightforward.

In [ ]:
geochemistry_df = pd.read_csv('Data/1207_Geochemistry.csv')
geochemistry_df

This data structure (the variable we've called `geochemistry_df`) is known as a `DataFrame`, or `df` for short (note the capitalization - this is important). You can think of it as an Excel spreadsheet on steroids, as it can have more than 2 dimensions (though this is difficult to visualize). All dataframes have an **index** (here from 0 to 70) and several `Series` - these are the columns in the table. As previously mentioned, this table is actually a NumPy array under the hood.

Because we will be using ODP/IODP data extensively in this course, let's define what the different `Series` (i.e., columns) represent.

* **Leg** refers to the particular expedition the drill ship was on. In more recent IODP cruises, this is referred to as the 'Expedition' or 'Exp'.
* **Site** refers to the name of the general area that was drilled, which is a sequential number. 
* We also have the 'Hole', which is shortened to **H** in this DataFrame. A hole is essentially a well, and a site can contain multiple nearby wells.
* **Cor** is short for core number 
* **T** is a letter that describes the specific tool used for coring. 
* **Sc** indicates the section of the core: each 9.8-m core is cut into 1.5-meter sections for easy handling, with the addition of the core catcher ('CC') which represents material not in the core liner. 
* **Top(cm)** indicates the depth of the sample from the top of the section in cm.

Thus, an ODP/IODP sample can be fully characterized by the combination of the parameters we have seen so far. for instance, the first sample in this dataframe is ODP Sample has the unique ID **198-1207-A-2-H-2-65**.

* **Depth (mbsf)** is the depth below the seafloor (in meters) of a particular sample, which can be calculated if you know the full name of the sample. 
* **CaCO3 (wt %)**: Finally, the last Series is the %-carbonate measured at this location. 

### Other filetypes

Although comma-separated values files (`.csv` files) are one of the most common file formats, it is not the only format used by data scientists. In fact, Pandas can read multiple formats just as easily, including JSON, Parket, and Excel, amongst others. Let's open a second dataframe but this time using the Excel format (NOTE: you may need to install xlrd, e.g. 'conda install xlrd'):

In [ ]:
ngr_df = pd.read_excel('Data/1207_NGR.xls')
ngr_df

As you can see, it was just as easy. Excel and CSV files are some of the most common formats you will be using. Note that it is easier to open the old `.xls` files rather than the newer `.xlsx` files, and there are reasons for this: while you can install extensions to open `.xlsx` files, it is not recommended as there are potential safety issues around this.

The only column that is different from the previous dataframe is the last one, the 'Corr. Counts' or 'corrected counts':
* **Corr. Counts** describes the natural gamma radiation measured on the cores. 

### 2.3.2 Dropping Entries from an Axis <a id="dropping"></a>

Sometimes, you want to drop an entry from a dataframe. For instance, the hole name of the sample may not be necessary to your analysis - it's always good to get rid of extraneous data to prevent it from clogging up your DataFrames. To drop the hole name (well name) from the dataset, we can use the 'drop' command. There are two ways to use it:
```python
df.drop(columns=['column1', 'column2', ...])
```
**OR**
```python
df.drop(['column1', 'column2', ...], axis=1) # Remember that axis 1 is the column axis, axis 0 the rows in a matrix
```
By default, the `drop()` method is applied to the rows. So, if you don't provide Pandas with an `axis` parameter, you can use it to drop rows like this:
```python
df.drop(['row1', 'row2', ...]) 
```
Of course, if you try to give the `drop()` function a column name without specifying an axis or the `columns` parameter, you will receive an error. 

That said, using the `drop()` command can be a little counter-intuitive to some. Let's try to drop the well name (column 'H') below, and see if the result is what you expect:

In [ ]:
geochemistry_df.drop(columns=['H'])
geochemistry_df

Can you spot the problem? The `H` column is still in our dataframe. So what did we do wrong? 

### 'in place' operations in Pandas

You might be surprised to hear that column `H` NOT being dropped in the above is a big and important feature of Pandas. It comes from one of the core concepts of functional programming: data structures should remain unchanged (i.e., data structures are 'immutable'). Thus, the default for most Pandas operations is to *not* change the existing dataframe, and instead return a new structure. Let's break down what happened so that we have a better understanding of what happened in the cell above:

* We asked Pandas to drop column `H` from our DataFrame
* Pandas created a copy of our DataFrame
* Pandas dropped `H` from the copy
* We asked Pandas to display the original `geochemistry_df` which, of course, is unchanged.

So, how can we deal with this? There are two ways to do that. First and probably the best way, we simply assign the new dataframe to a new variable:

In [ ]:
mod_df = geochemistry_df.drop(columns=['H'])
mod_df

It worked! But imagine now a situation where we have a dataset of several gigabytes. What would happen then? Because we created a copy of this dataframe while also keeping the original DataFrame in memory, we'll run out of computer memory really quickly.

This is why sometimes it makes sense to do operations on the actual data itself, even if this removes data permanently from the original dataset. Of course, one approach is to reassign the new dataframe to the same variable name:

In [ ]:
geochemistry_df = geochemistry_df.drop(columns=['H'])
geochemistry_df

But there is a more elegant solution: using the Pandas `inplace` keyword. `inplace` works with most operations in Pandas that would normally return a copy of the data. In other words, the default value for `inplace` is `False` because it returns a copy of the data. Let's do this for our dataset:

In [ ]:
# I need to reload the data as I already dropped 'H' in my previous example.
# This is one reason why you need to be very careful about removing data from your original dataset - you can't get it back 
# without reloading the data!
geochemistry_df = pd.read_csv('Data/1207_Geochemistry.csv')

# Using 'inplace':
geochemistry_df.drop(columns=['H'], inplace=True)
geochemistry_df

As you can see, our code now works as expected. Be careful though, it is easy to get confused with the return values. When `inplace` is `False` the function returns a new dataframe. But when inplace is set to `True`, the function returns nothing - it merely updates the original DataFrame. So be sure **NOT** to combine the two methods (i.e. do not assign it to itself if `inplace==True`), as in the example below:

In [ ]:
# Do Not Do This

# I need to reload the data as I already dropped 'H' in my previous example:
geochemistry_df = pd.read_csv('Data/1207_Geochemistry.csv')

# Using 'inplace' and assigning it to the same variable name:
geochemistry_df = geochemistry_df.drop(columns=['H'], inplace=True)

# Let's check the type of this new data
type(geochemistry_df)

As you can see, we have a `NoneType` now and of course any operations on this would not work.

## Exercise 2 

Reload a fresh version of `geochemistry_df` as we erased it with a `NoneType` before. And create a new dataframe (let's call it `geochemistry_mod_df`) that is a copy of `geochmistry_df` but without the well, core and tool columns. Call this new dataframe `geochemistry_mod_df`.

In [ ]:
# Your code here

geochemistry_df = 
geochemistry_mod_df =

### 2.3.4 Indexing, Selection, Filtering, and Sorting <a id="indexingdf"></a>

Of course, in many cases we won't want to do operations on the *entire* DataFrame. Often, we'll just want to make changes to/analyse one of the columns.

This section will further your understanding of how to extract and filter data out of a dataframe. You can extract a Series in a DataFrame by calling it by name (make sure you reload the original geochemistry_df file):

In [25]:
geochemistry_df['CaCO3 (wt %)'] 

NameError: name 'geochemistry_df' is not defined

Watch out! Column indexing is case sensitive and typos will lead to a "column not found" error if you're not careful. **Pro tip:** The 'tab' autocompletion also works for column names in dataframe. So, to avoid an error, if I type `geochemistry_df['Ca <tab>']` Jupyter will autocomplete the name of the column for me.

You can extract more than one series at a time by passing a list of names:

In [ ]:
# Note how you need 'two' square brackets for this!
geochemistry_df[['Depth (mbsf)','CaCO3 (wt %)']]

Note that all of these operations return a new DataFrame, so if you want to use them later in your code, you'll need to assign them to a new variable:

In [ ]:
depth_vs_carbonate_df = geochemistry_df[['Depth (mbsf)','CaCO3 (wt %)']]
depth_vs_carbonate_df

You can also extract a list of samples based on Boolean criteria (remember, "Boolean" just means a True or False condition). For instance, the following code will return a Series containing the value `True` for samples that have `CaCO3 (wt %)` >=50% and `False` otherwise:

In [ ]:
geochemistry_df['CaCO3 (wt %)'] >=50

What's interesting is that you can pass this Boolean series to a DataFrame: if you do, the DataFrame will be filtered based on the values in this list, returning a new dataframe that only contains rows in which the condition is `True`. Thus, the code below will return a new dataframe that only contains samples in which the carbonate content was greater than or equal to 50%:

In [ ]:
# Look at the index of the returned DataFrame - you can see that some of the samples are missing!
geochemistry_df[geochemistry_df['CaCO3 (wt %)'] >=50]

You can of course filter for more than 1 condition. When filtering on more than one condition, you need to surround each condition with a pair of `()`. In this example, notice that I have separated each statement by an `&`, which is the Python operator for logical `AND`:

In [ ]:
geochemistry_df[(geochemistry_df['CaCO3 (wt %)'] >=50) & (geochemistry_df['Depth (mbsf)'] <100)]

You can also use a logical `OR` to filter your data: in Python, this is signified by the `|` (this is known as a pipe symbol). Thus, in this example, I will return all samples that were above 100 mbsf regardless of its carbonate content **AND** all the samples below 100 mbsf with >=50% carbonates:

In [ ]:
geochemistry_df[(geochemistry_df['CaCO3 (wt %)'] >=50) | (geochemistry_df['Depth (mbsf)'] <100)]

You can combine 'OR' and 'AND' logic to your heart's content. You can use '()' to tell Pandas the order of operations for the Boolean criteria, similar to how you would use it in algebra. In the case below, it will return all the data from the previous query above, while limiting it to samples below 150 mbsf (notice the `&` at the end)

In [ ]:
# If you're confused, try writing out the logic in words using a pen and paper.
geochemistry_df[((geochemistry_df['CaCO3 (wt %)'] >=50) | (geochemistry_df['Depth (mbsf)'] <100)) & (geochemistry_df['Depth (mbsf)'] <150)]

### Selecting data using loc and iloc

You can also access data in your dataframe using the `.loc` method (stands for 'location') and `.iloc` method ('index location').

Let's first use `loc`, and return the `CaCO3 (wt %)` column for the rows at index 1 and 10:

In [ ]:
geochemistry_df.loc[[1, 10], 'CaCO3 (wt %)'] 

In [ ]:
# The ':' sign is shorthand for 'all'. For instance, this will output all columns for the selected samples:
geochemistry_df.loc[[1, 10],:] 

In [ ]:
# Or all samples for the selected column:
geochemistry_df.loc[:,'CaCO3 (wt %)']

Similar to when you sliced ndarrays, you can slice the DataFrame using `loc`:

In [ ]:
geochemistry_df.loc[1:4,'CaCO3 (wt %)'] # This returns carbonate content for samples from index 1 to 4

In [ ]:
# iloc works similarly to loc, but uses the index position of the row and columns. So, here we take rows 7 to 27, and columns 7 (Depth) to the end (CaCO3)
geochemistry_df.iloc[7:27, 7:]

### Sorting Series and DataFrames

You can sort a DataFrame by its index, or by a specific column. Here, we sort our geochemistry DataFrame by its index:

In [ ]:
# No observable change - the df was already sorted!
geochemistry_df.sort_index()

To reverse sort it:

In [ ]:
geochemistry_df.sort_index(ascending = False)

Sorting a series is done using `sort_values()` method:

In [ ]:
geochemistry_df['CaCO3 (wt %)'].sort_values()

Additionally, you can sort (or reverse sort) an entire dataframe by your preferred column. Here, we sort the entire DataFrame by the %-carbonate

In [ ]:
geochemistry_df.sort_values(by='CaCO3 (wt %)')

Here is a slightly more involved example, where we reverse sort by %-carbonate followed by depth. You can have as many columns in the list that you pass to the `by` parameter as you wish:

In [ ]:
geochemistry_df.sort_values(by=['CaCO3 (wt %)', 'Depth (mbsf)'], ascending=False)

### Creating and Manipulating Columns

There are many cases where you would like to create new columns based on the values of existing columns or adjust existing columns in order to make them more consistent across the DataFrame. For example, one might want to convert `Top(cm)` into meters in order to be consistent with the units used in the `Depth (mbsf)` column.

Pandas makes this easy - you simply need to assign your adjusted column to the original column:

In [ ]:
# Convert cm to m by dividing by 100 and assigning it to the original column
geochemistry_df["Top(cm)"] = geochemistry_df["Top(cm)"] / 100

geochemistry_df

That said, this may not always be what you want to do, since this modifies the original data. This can be potentially dangerous: try running the cell above multiple times - what issue can you spot? 

That's right, since you're modifying the original data and reassigning the new values to the original column, the values in the `Top(cm)` column get smaller and smaller every time you run the cell! This can lead to several bugs and may be difficult to catch. 

Instead, a more prudent way of approaching this problem is to *create* a new `Top(m)` column that contains the appropriate measurement. This is as simple as repeating the above cell, but instead of assigning the value to `Top(cm)`, you merely assign it to `Top(m)` - Pandas will create the new column for you!

In [ ]:
# Re-import the original data so that the Top(cm) column is back to normal
geochemistry_df = pd.read_csv('Data/1207_Geochemistry.csv')

# Assign the adjusted values to the new Top(m) column
geochemistry_df['Top(m)'] = geochemistry_df["Top(cm)"] / 100

geochemistry_df

## Summarizing and Computing Descriptive Statistics

You can do the same descriptive statistics on a DataFrame or a Pandas Series that you would on an ndarray.

`describe()` is a very useful method that gives you a quick sense of the nature of your dataframe in an easy-to-digest format:

In [ ]:
# Be careful - describe will return statistics of all numeric columns, even in columns where it would not make sense (look at
# the 'Leg' and 'Site' columns)
geochemistry_df.describe()

Note that only the numerical columns were used in the `describe()` method. You can also limit the description to one series (column):

In [ ]:
geochemistry_df['CaCO3 (wt %)'].describe()

You can sum all of the columns:

In [ ]:
geochemistry_df.sum()

Interesting, but summing values on some columns do not make a lot of sense because they are not numerical (for instance, `H` and `T`). It is time to learn to filter a DataFrame by data type!

#### Filtering by data type

We can call the `dtype` argument on any Series to check its data type:

In [ ]:
geochemistry_df['CaCO3 (wt %)'].dtype

This might be a little confusing to some of you: `float64` indicates that the datatype is numeric, and describes how the number is encoded. `float` means that the number encoded is a float (in contrast to a datatype like `int32`), while 64 indicates that the number is stored using 64 bits. The more bits you use to store a number, the bigger the stored number can be, but the more space it will take up in memory. Look up the difference between `float32` and `float64` to see the difference in the size of number that can be stored.

We can also look at the data type of each columns in a dataframe using `dtypes`:

In [ ]:
geochemistry_df.dtypes

Notice that strings are given the `object` data type in Pandas and NumPy. 

Let's filter our DataFrame and keep only the `float64` and `int64` values before taking our sum:

In [ ]:
geochemistry_df.select_dtypes(['float64','int64']).sum()

Note that `.select_dtypes(['float64','int64'])` returns a new Series, and we could have saved this as a variable. But the example above shows you a very common use of Pandas, where operations are **chained together** to obtain a result. Chaining operation is another main reasons Pandas tends to return copies of Dataframes rather than do transformations in place: that way, we can perform the subsequent operation on the output of the previous function.

Selecting numeric values in this way can be a little inefficient, since you need to make sure that you specify every numeric dtype in the column (e.g., `float64`, `int64`, `float32`, `int32`). We can simplify this by specifying that you want `include = np.number` to select numeric datatypes only:

In [ ]:
geochemistry_df.select_dtypes(include = np.number).sum()

**Bonus Task**: Use Shift-Tab to read through the `select_dtypes` documentation to find out how to select string columns only.

We can also do summary statistics by row. If you want to add the values in each column together per row, use this syntax:

In [ ]:
geochemistry_num_df = geochemistry_df.select_dtypes(include = np.number)

geochemistry_num_df.sum(axis='columns')

We can calculate the cumulative sum (even though it doesn't make much sense in this context):

In [ ]:
geochemistry_num_df.cumsum(axis='columns')

Another useful statistic is the percentage change between two consecutive values. The following code calculates the % change between a row and the preceding row in the %-carbonate column:

In [ ]:
geochemistry_df['CaCO3 (wt %)'].pct_change()

We can also look at the correlation between two series:

In [ ]:
geochemistry_df['CaCO3 (wt %)'].corr(geochemistry_df['Depth (mbsf)'])

Or the covariance between two values:

In [ ]:
geochemistry_df['CaCO3 (wt %)'].cov(geochemistry_df['Depth (mbsf)'])

You can also very quickly assess the correlation between all of the series in your dataframe:

In [ ]:
# Note: This will fail if your DataFrame has any string-containing columns. Make sure you filter those out before running .corr()
geochemistry_num_df.corr()

And the same with covariance:

In [ ]:
geochemistry_num_df.cov()

# Exercise 3

Write a one-line program that outputs a series of boolean (`True` or `False`) that indicates whether the mean of each numeric column in the `geochemistry_df` is >100. **Tip:** You will need to chain operations.

In [ ]:
# Your Code

### 2.3.5 Joining and Merging Datasets <a id="combine"></a>

You will often find yourself with multiple datasets that need to be merged together. For example, you might have a dataset like `geochemistry_df` that contains all of the details of each core, as well as a separate dataframe containing a geologist's interpretation of the lithologies in each sample. In such cases, you may wish to merge these two datasets into a single DataFrame, either along their index (i.e., you add new Series/columns to your data) or by concatenating the data along one of the two axes, such as when you want to add new records (rows) to the dataset. Let's explore how this is done in Pandas.


#### Merging on Index

Let's assume that you have two dataframes with at least some overlap in their index. This could be for instance an index that is based on the depth below the surface, or the sample name. You are then interested in merging the series (columns) that are common between the two datasets together. For this, you need to merge along the index.

In [26]:
# Let's create two very simple dataframes for this example. 
# This will also show you how to create dataframe programmatically using a dictionary:

mineralogy = pd.DataFrame({'mineral': ['calcite', 'dolomite', 'quartz', 'quartz', 'calcite', 'quartz'],
                           'color': ['yellow', 'pink','grey', 'grey','white','pink'],
                           'depth (m)':[2.,4.,6.,8.,10.,12.]}, 
                          index=['sample 1', 'sample 2','sample 3','sample 4','sample 5','sample 6'])
mineralogy

NameError: name 'pd' is not defined

In [ ]:
formation_name = pd.DataFrame({'formation': ['Shuaiba', 'Greyburg', 'Farah', 'Farah', 'Shuaiba'],
                               'depth (m)':[2.,6.,8.,14.,10.] }, 
                              index=['sample 1', 'sample 3','sample 4','sample 7','sample 5'])
formation_name

We can `merge` the two DataFrames, which only returns records (rows) for which we have data in **both** dataframes. This is also known as an **inner join**. Setting `left_index` and `right_index` to `True` tells the merge function that we want to use the index as the "key" on which to join our DataFrame (in other words, `merge` will use the index of both DataFrames to find matching records).

In [ ]:
pd.merge(mineralogy, formation_name, left_index=True, right_index=True)

**Bonus Exercise**: One thing to note is that the `pd.merge` function defaults to `how = 'inner'` when deciding how to join the two DataFrames. However, there are other types of 'join' that you can use to merge your data, including `'left'`, `'right'`, and `'outer'`. Use the cell below to experiment with the `how = ` parameter and try to understand what each of these joins are doing.

In [ ]:
pd.merge(mineralogy, formation_name, how = '...', left_index=True, right_index=True)

Another way of joining two DataFrames together is the `pd.concat` function (short for 'concatenate), passing the `axis` as a parameter. 

Here we concatenate the two DataFrames along their columns (axis 1), and we want to drop rows where we don't have all the data using `join = "inner"`:

In [ ]:
pd.concat([mineralogy,formation_name], join="inner", axis=1)

That said, be careful of using this method of concatenating DataFrames: concatenation does not care about column names when joining the two dataframes together. If you look at the cell above, you can see we have two `depth (m)` columns. Having duplicated column names can lead to bugs that are difficult to catch. Furthermore, dropping duplicated columns is more difficult than you'd think!

Nevertheless, one thing that `pd.concat` is very good for is adding new rows to our data. For instance, if we create a new dataframe with new samples:

In [ ]:
mineralogy_extended = pd.DataFrame({'mineral': ['calcite', 'quartz'],
                                    'color': ['white','pink'],
                                    'depth (m)':[14.,16.]}, 
                                   index=['sample 7', 'sample 8'])
mineralogy_extended

We can concatenate this data to the old mineralogy to add rows.

In [ ]:
#NB the axis = 0 parameter is optional, as if no axis is stipulated, Pandas assumes it is 0.
pd.concat([mineralogy,mineralogy_extended], join="inner", axis=0)

## Exercise 4

In this exercise, you will need to use your skills in data manipulation in Pandas to answer the following simple question:

*What is the average carbonate content of samples from ODP Site 1207 where the gamma ray count is >30?*

You have all of the data you need to answer this question in the two datasets we have uploaded from the files before (`geochemistry_df` and  `ngr_df`). However, they currently are in separate dataframes. The goal of this exercise is also to teach you some new methods, and to do this cleanly using functions. Remember, functions are great because we can reuse the code!

### Guidance:
Do the following:
1. In order to merge the dataset, we will use the `Depth (mbsf)` column in both files as the key for the merge, but rounded to the closest full meter. Why the rounding? Otherwise, you will only have 4 samples with the exact same depth. If we round the values first, we will have more overlap between the two datasets. Check the documentation for the Pandas `.round()` method to learn how to use it.
2. Write a simple function that takes a dataframe as an argument, and outputs a copy of this dataframe but with the `Depth (mbsf)` column rounded to the nearest meter. I have given you below the function's signature, i.e. its name and the main argument (`def round_depth(df)`). Replace the `pass` with the code needed for this function. **Bonus**: Can you do this without making changes to the original DataFrame?
3. Write a second function (`merge_by_depth(df1,df2)` below) that takes two dataframes, and returns a new, merged dataframe using the `Depth (mbsf)` column for the merge.
4. Finally, apply the two functions above to merge the `geochemistry_df` and  `ngr_df` dataframes, and calculate the mean value of carbonate content for samples with a `Corr. Counts` larger than 30.

In [ ]:
# Your Code:

# This simple function returns a copy of the dataframe with rounded values
def round_depth(df):
    pass

# This other simply function returns a merged version of the dataset
def merge_by_depth(df1,df2):
    pass

<details>
<summary><b>Click here to check whether you got the right answer to part 4 of the Exercise</b></summary>

The correct answer is 5.03125

</details>

# Feedback Form

In [1]:
%%html 
<iframe src="https://forms.gle/vf3E1SqQDAgWfHYz7" width="800" height="600" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>